### PR TITLE
add ability to stub out a relative or absolute path command call

### PR DESCRIPTION
**Pull request by mdurban**

### CODE REVIEW

**Comment by bennyhat** [comment]
Does this test cases where an absolute path is called inside of a script, rather than directly by the execute_function ?

Otherwise, this looks good

**Comment by mdurban** [comment]
Tests still needed, don't merge.

Oh yeah, and apparently Rubocop is still a thing...

**Comment by mdurban** [comment]
This PR is so old that I need to see if my new changes make sense with my old ones.

So don't merge.

**Comment by mdurban** [comment]
I actually hate this solution (adding the path to the temporary folder where it creates the stubs) so I'll probably try something else. Do you have any ideas?

**Comment by bennyhat** [comment]
Here are some things to consider, if you want to try a different route:
- Making the stub match the path is not strictly necessary, as long as the function with the absolute path in it points to the right place. Ex. function /my/path/to/command {\n /tmp/something/1234 $@\n} would work. Once again, PATH is not so important, since we added in the function stubbing part.
- Given that, you could generate a random file name for the stub and place it in the temp dir (or anywhere really). However, the only other thing to keep in mind, is that the stub currently find its <name>_call.yaml and <name>_stub.yaml files by looking at the basename of the file that's executing. Ex. if you make the temp file /tmp/something/1234 it will try and find 1234_calls.yaml, etc. The branch I'm working on now makes that less of a burden by turning the stub into an erb, where you could just inject the command name, but it's not quite ready yet.

**Comment by bennyhat** [comment]
Here is the branch I've been working in. I'm almost ready to submit a pull request. Need to remove some duplicate tests and add some more for stdin and calls.

https://github.com/mdurban/rspec-bash/compare/master...mdurban:21-argument-wildcards

**Pull request closed without merging**
